### ISSUE TITLE
Automate the generation of Taichi contributors

### ISSUE THREAD

**Issue by rexwangcc** [taichi-dev/docs.taichi.graphics#24]
Currently contributors are listed here at https://taichi.graphics/community/members.html#active-contributors by manual markdown editing, while it's necessary to maintain Technical Steering Committee, Committers and Reviewers lists maunally, it would be better if we could have a more automated way to display active contributors.

Existing solutions include:
- Write a script and CI job to automatically update the list of contributors from Github (multiple repos). **Example:** https://fastapi.tiangolo.com/fastapi-people/
- Use integrations provided by [Open Collective](https://opencollective.com/). **Example:** https://github.com/SpaceVim/SpaceVim#support-spacevim

_For the initial implementation, we don't have to go fancy as including images and names, simply generating a list of Github user ids might be enough._

**Comment by yuanming-hu** [comment]
I agree that in the beginning, a periodic semi-automatic update sounds good. Here's a script to generate a list of active contributors: https://github.com/yuanming-hu/taichi/blob/master/misc/fetch_active_contributors.py

**Comment by rexwangcc** [comment]
Resolved by https://github.com/taichi-dev/public_files/blob/master/.github/workflows/update_avatars.yml, and we ended up going down the fancy path lol.
