### ISSUE TITLE
[Need to update]: Clang dependence of Arch Linux building guide 

### ISSUE THREAD

**Issue by Axe-hyx** [taichi-dev/docs.taichi.graphics#92]
https://github.com/taichi-dev/docs.taichi.graphics/blob/master/website/docs/lang/articles/contribution/dev_install.md#installing-dependencies
Currently clang-10 is not available in pacman package repository, I successfully built `taichi==0.8.0` with clang and llvm prebuild with [this](https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz) release pack.

**Comment by yuanming-hu** [comment]
Hi @Axe-hyx, thanks for raising this issue. Could you post this thread to https://github.com/taichi-dev/taichi/issues? This repo is just  an automatic deployment - the real doc is here: https://github.com/taichi-dev/taichi/tree/master/docs/lang
